spring:
  datasource:
    url: jdbc:mysql://localhost:3306/file_center?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.sample.app.entity
  global-config:
    db-config:
      id-type: INPUT

app:
  file-server:
    type: aliyun
    #oss配置
    oss:
      access-key: 
      accessKeySecret: 
      endpoint: 
      bucketName: 
      # 上传路径不能以/开头，要以/结尾，示例(xxx/xxx/)
      path: upload/video/
      expireYear: 10
  swagger:
    enabled: true
    title: 文件中心
    description: 文件中心接口文档
    version: 1.0
    base-package: com.sample.app.controller
  #多租户配置
  tenant:
    enable: true
